### ISSUE TITLE
master分支mvn不通过

### ISSUE THREAD

**Issue by LeiRui** [thulab/iotdb#436]
下载最新的tsfile、iotdb-jdbc、iotdb之后，对iotdb执行mvn clean package报错如下：

> Results :
> 
> Failed tests: 
>   AggregationSmallDataTest.test:140->countOnlyTimeFilterTest:585 meet error in get QueryDataSet because null
>   DaemonTest.test:155->aggregationTest:582 meet error in get QueryDataSet because null
>   LargeDataTest.test:110->aggregationWithoutFilterTest:297 meet error in get QueryDataSet because null
> 
> Tests run: 299, Failures: 3, Errors: 0, Skipped: 1

 Can this problem be reproduced or just my problem?

**Comment by MyXOF** [comment]
这个问题会在add_timing_opened_file_manager分支解决
