### ISSUE TITLE
重命名

### ISSUE THREAD

**Issue by qiaojialin** [thulab/iotdb#485]
将 cn.edu.tsinghua.tsfile.timeseries.filter.expression 下的类改名为 expression

改动包结构
原：
cn.edu.tsinghua.tsfile.timeseries.read
cn.edu.tsinghua.tsfile.timeseries.write
cn.edu.tsinghua.tsfile.timeseries.filter
cn.edu.tsinghua.tsfile.timeseries.utils

改动后：
cn.edu.tsinghua.tsfile.read
cn.edu.tsinghua.tsfile.write
cn.edu.tsinghua.tsfile.read.filter
cn.edu.tsinghua.tsfile.utils

**Comment by jixuan1989** [comment]
I will close this issues because #497  PR has fixed it.
