### ISSUE TITLE
Modify Grafana Pom

### ISSUE THREAD

**Issue by jixuan1989** [thulab/iotdb#501]
Do not use spring-boot-starter-parent as the parent. Use iotdb-root instead.

**Comment by MyXOF** [comment]
这个不好改动。
spring-boot-starter-parent 有非常多，非常多，非常多的依赖，不知道哪些有用，哪些没用。而且我找了好多资料，包括官方教程里面都是用spring-boot-starter-parent作为parent（https://github.com/spring-guides/gs-spring-boot/blob/master/complete/pom.xml）。建议还是保留这种写法，后续grafana可以作为单独的一个小工具不开源吧。

**Comment by wujysh** [comment]
Try with `spring-boot-dependencies`?

**Comment by MyXOF** [comment]
这不光是一个依赖的问题，还有许多打包的插件在里面，打出war之后具体怎么执行都在parent里面设置好了

**Comment by wujysh** [comment]
还有这个插件 spring-boot-maven-plugin

**Comment by MyXOF** [comment]
有eclipse的话，可以看下它的effective pom，有3000多行，不知道这里面哪些有用哪些没用

**Comment by MyXOF** [comment]
你说的那个插件我试试

**Comment by wujysh** [comment]
其实应该就是引了这个 https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml

**Comment by wujysh** [comment]
具体哪些用了哪些没用确实不好整理。。

**Comment by MyXOF** [comment]
对啊，搞了一下午，放弃了

**Comment by jixuan1989** [comment]
Switch our discussion (at least some conclusions) in English.
