### ISSUE TITLE
cn.edu.tsinghua.iotdb.queryV2.engine.control.OverflowFileStreamManager uses the deprecated internal SUN API which is not available in Java 11 anymore

### ISSUE THREAD

**Issue by jixuan1989** [thulab/iotdb#503]
cn.edu.tsinghua.iotdb.queryV2.engine.control.OverflowFileStreamManager uses the deprecated internal SUN API which is not available in Java 11 anymore
try to replace the related API

**Comment by xingtanzjr** [comment]
Which API ?

**Comment by jixuan1989** [comment]
@xingtanzjr see: https://travis-ci.org/thulab/iotdb/jobs/466919744
