### ISSUE TITLE
fix problem discovered by sonar of my code

### ISSUE THREAD

**Issue by liuruiyiyang** [thulab/iotdb#516]
The newly applied CI tool Sonar can  help us detect bugs, vulnerabilities, code smell and so on. By clicking My Issues button the system will display the report related to individual committer, as shown in the following screenshot.
<img width="1334" alt="2018-12-14 10 48 07" src="https://user-images.githubusercontent.com/20263106/49980346-10608500-ff8e-11e8-949a-7697fd3aa98e.png">

Besides, there are some obsolete comment and code naming in OpenFileNumUtil.java since new data directory is applied, which needs to be fixed.

**Comment by jixuan1989** [comment]
can we close the issue? @liuruiyiyang
