### ISSUE TITLE
maybe a concurrent error when multi-client insert a new data into memtable

### ISSUE THREAD

**Issue by jixuan1989** [thulab/iotdb#520]
I noticed that we do not obtain any lock when write data in memtable.

Suppose two client send data to IoTDB,  one writes `d1.s1` and meanwhile the other writes `d1.s2`. If both of them run `memTableMap.put(deltaObject, new HashMap<>());`, then we will lost some data.

see `AbstractMemTable.java`:

```java
    private IMemSeries createIfNotExistAndGet(String deltaObject, String measurement, TSDataType dataType) {
        if(!memTableMap.containsKey(deltaObject)) {
            memTableMap.put(deltaObject, new HashMap<>());
        }
        Map<String, IMemSeries> memSeries = memTableMap.get(deltaObject);
        if(!memSeries.containsKey(measurement)) {
            memSeries.put(measurement, genMemSeries(dataType));
        }
        return memSeries.get(measurement);
    }
```

**Comment by jixuan1989** [comment]
@liuruiyiyang  can you try to reproduce the scenario?
@liukun4515  can you confirm it logically?
By the way,  when a user write data, and at the same time, a flushing operation occurs, what will happen?

**Comment by liukun4515** [comment]
A thread can call the interface of memtable, it should acquire the lock in the corresponding filenode first.
@jixuan1989

**Comment by liukun4515** [comment]
> By the way, when a user write data, and at the same time, a flushing operation occurs, what will happen?
The data is written into the memtable, which will be flushed in a background thread.
At the same time, we will give a new memtable which is used to store newly written data.

**Comment by xingtanzjr** [comment]
> 
> 
> > By the way, when a user write data, and at the same time, a flushing operation occurs, what will happen?
> 
> The data is written into the memtable, which will be flushed in a background thread.
> At the same time, we will give a new memtable which is used to store newly written data.



> 
> 
> > By the way, when a user write data, and at the same time, a flushing operation occurs, what will happen?
> 
> The data is written into the memtable, which will be flushed in a background thread.
> At the same time, we will give a new memtable which is used to store newly written data.

So this problem doesn't exist, right ?

**Comment by jixuan1989** [comment]
But I think it is a coarse-grained implementation. It limits the concurrency. 
Anyway, current implementation is correct.

**Comment by liukun4515** [comment]
> But I think it is a coarse-grained implementation. It limits the concurrency.
> Anyway, current implementation is correct.

The method of concurrent control must limit the concurrency, but we should do something else synchronously for each filenode processor before data to be written into the memtable.
@jixuan1989
