### ISSUE TITLE
OpenFileNumUtilTest Failed in ut of IoTDB

### ISSUE THREAD

**Issue by MyXOF** [thulab/iotdb#536]
**Describe the bug**
Failed to run ut in iotdb if there are more than one procees in the pipeline
package cn.edu.tsinghua.iotdb.utils
Class: OpenFileNumUtilTest

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by liuruiyiyang** [comment]
Since our CI pipeline has mutiple current builds and tests, the test files created by different builds may  have the same name, which leads to the error and is not considered before. I think.

**Comment by MyXOF** [comment]
but they are located at different directories, at such case, will they conflict?

**Comment by liuruiyiyang** [comment]
I tried to reproduce the error by executing 2 tests concurrently using command ```mvn clean test -pl iotdb -am -Dtsfile.test.skip=true -Djdbc.test.skip=true -Dit.test.excludes="**/IoTDB*Test.java"```, however I can't reproduce it. And I inspected the CI build history but I have no clue when this problem will occur...

**Comment by MyXOF** [comment]
you can just push codes to remote repo which triggers two CI build(iotdb_ut_linux, iotdb_ut_jdk_9_linux). Now in master branch, i have ignored your tests
@liuruiyiyang
