### ISSUE TITLE
ineffective configuration parameter

### ISSUE THREAD

**Issue by CUTEYANSHU** [thulab/iotdb#563]
The parameter ```wal_cleanup_threshold``` in ```iotdb-engine.properties``` is ineffective. Is this parameter going to be applied in future version or just redundant?  

BTW the description of parameter ```flush_wal_threshold``` :  
```
# When a certain amount ofwrite ahead log is reached, it will be flushed to disk
# It is possible to lose at most flush_wal_threshold operations
```
the word ```operations``` is confusing.

**Comment by jixuan1989** [comment]
wal_cleanup_threshold is useful in our design, I think.
@jt2594838 and @liuruiyiyang  can you double-check it?

**Comment by CUTEYANSHU** [comment]
@MyXOF 
Oh I see,  there were some problems of my IDE, now it is fixed, the ```tsfile-format.properties``` did effective. Thank you.

**Comment by liuruiyiyang** [comment]
Thanks for your feedback, ```wal_cleanup_threshold``` will be removed in the next PR which handles current WAL perf issue.
